import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "@/components/LegalPage";
export const metadata: Metadata = { title: "Terms and Conditions", description: "Terms covering the Auric Performance website, coaching and programmes." };
const sections: LegalSection[] = [
  { title: "1. About these terms", body: <><p>Auric Performance, 25 Station Road, Hatch Beauchamp, Taunton, TA3 6SQ, provides coaching, exercise programming, rehabilitation and related services. By using the website or purchasing a service, you agree to the applicable terms. Your statutory consumer rights remain protected.</p></> },
  { title: "2. Services and eligibility", body: <p>The exact scope, duration, delivery method and included features are shown on the relevant programme page, checkout, proposal or confirmation. Purchasers must be 18 or have the involvement and consent of a parent or legal guardian.</p> },
  { title: "3. Orders, prices and payment", body: <p>A contract is normally formed when we accept your order, confirm a coaching place or take payment and provide access. Prices and billing intervals are shown before purchase. Failed or overdue payments may result in suspended access or cancellation.</p> },
  { title: "4. Subscriptions and cancellation", body: <p>Recurring-service details, any minimum term and renewal arrangements are shown at checkout. Unless stated otherwise, cancelling stops future renewals at the end of the paid period. UK consumers purchasing at a distance will usually have a 14-day cancellation right, subject to exceptions for services or digital content started immediately with consent.</p> },
  { title: "5. Appointments", body: <p>Please provide at least 24 hours’ notice to cancel or rearrange a live appointment unless different terms were agreed. Late cancellations or missed sessions may be treated as used. If we cancel and cannot provide a reasonable replacement, the affected element will be credited or refunded.</p> },
  { title: "6. Health and safety", body: <p>You must provide relevant and accurate health and injury information, use equipment safely, follow reasonable instructions and stop if concerning symptoms occur. Seek advice from an appropriately qualified healthcare professional where necessary. In an emergency, contact the emergency services.</p> },
  { title: "7. Results and responsibilities", body: <p>Results depend on factors including consistency, health, recovery, nutrition and circumstances. We provide services with reasonable care and skill but cannot guarantee a particular result. Testimonials describe individual experiences only.</p> },
  { title: "8. Digital content and intellectual property", body: <p>Programmes and materials are for the purchaser’s personal, non-commercial use. They may not be copied, shared, resold, recorded or distributed without written permission. Access may end when a subscription or service ends.</p> },
  { title: "9. Liability and third parties", body: <p>Nothing excludes liability where doing so would be unlawful. Subject to consumer law, we are not responsible for losses that were not reasonably foreseeable or caused by information you withheld, failure to follow instructions or a third-party service outside our control.</p> },
  { title: "10. Complaints and governing law", body: <p>Contact info@auricperformance.co.uk first so we can try to resolve a concern. These terms are governed by the law of England and Wales, while consumers retain any mandatory right to bring proceedings in another applicable UK jurisdiction.</p> },
];
export default function TermsPage() { return <LegalPage kicker="Website & service terms" title="Terms & conditions" intro="Terms governing the website, coaching, programmes and related services." sections={sections} />; }
