import type { Metadata } from "next";
import LegalPage, { type LegalSection } from "@/components/LegalPage";
export const metadata: Metadata = { title: "Privacy Policy", description: "How Auric Performance collects, uses and protects personal information." };
const sections: LegalSection[] = [
  { title: "1. Who we are", body: <><p>Auric Performance provides physical performance coaching, programming and exercise rehabilitation. The data controller is Auric Performance, 25 Station Road, Hatch Beauchamp, Taunton, TA3 6SQ. Contact: info@auricperformance.co.uk.</p></> },
  { title: "2. Information we collect", body: <><p>We may collect your contact details, enquiry and client information, training goals, coaching records, payment status, website usage information and communications with us. Where relevant to safe coaching or rehabilitation, you may choose to provide health, injury and performance information.</p></> },
  { title: "3. How we use information", body: <><p>We use information to respond to enquiries, assess suitability, deliver and review services, manage appointments and payments, provide FITR access, maintain security, improve our services, meet legal obligations and send marketing where permitted.</p></> },
  { title: "4. Lawful bases and health information", body: <><p>Our lawful bases may include taking steps before a contract, performing a contract, legal obligations, legitimate interests and consent. Health information may be special-category data and is used only where relevant to suitability, safety or programme delivery, normally with explicit consent where required.</p><p>Coaching information is not a substitute for medical diagnosis or treatment.</p></> },
  { title: "5. Sharing and international transfers", body: <><p>We do not sell personal information. We may share necessary information with hosting, communication, coaching-platform, payment, accounting or professional service providers and public authorities where legally required. Some providers may process data outside the UK; where this happens, appropriate legal safeguards are used.</p></> },
  { title: "6. Retention and security", body: <><p>We retain information only as long as needed for service delivery and legal, tax, insurance or dispute-resolution purposes. Client and contractual records may commonly be retained for up to six years after service ends. We use reasonable organisational and technical safeguards, but no online system can be guaranteed completely secure.</p></> },
  { title: "7. Your rights", body: <><p>Depending on the circumstances, you may have rights to access, correct, erase, restrict or object to processing, request portability, withdraw consent and complain to the UK Information Commissioner’s Office. Contact us to exercise a right. We may need to verify your identity.</p></> },
  { title: "8. Marketing, children and external links", body: <><p>You may opt out of marketing at any time. Our services are not directed at children purchasing independently; a parent or guardian may need to act for anyone under 18. External platforms such as FITR, Google and payment providers operate under their own privacy notices.</p></> },
];
export default function PrivacyPage() { return <LegalPage kicker="Legal & data protection" title="Privacy policy" intro="How we collect, use, store and protect personal information." sections={sections} />; }
